package GameApi;

/**
* GameApi/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Tuesday, June 23, 2020 8:11:47 AM IST
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApi.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (GameApi.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApi.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApi.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApi.AdminHelper.type ();
  }

}
