package GameApi;


/**
* GameApi/Hashtable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Tuesday, June 23, 2020 8:11:46 AM IST
*/

public final class Hashtable implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public GameApi.Map value[] = null;

  public Hashtable ()
  {
  } // ctor

  public Hashtable (String _key, GameApi.Map[] _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class Hashtable
