package GameApi;


/**
* GameApi/hashmapHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Tuesday, June 23, 2020 8:11:46 AM IST
*/

abstract public class hashmapHelper
{
  private static String  _id = "IDL:GameApi/hashmap:1.0";

  public static void insert (org.omg.CORBA.Any a, GameApi.Map[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameApi.Map[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = GameApi.MapHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (GameApi.hashmapHelper.id (), "hashmap", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameApi.Map[] read (org.omg.CORBA.portable.InputStream istream)
  {
    GameApi.Map value[] = null;
    int _len0 = istream.read_long ();
    value = new GameApi.Map[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = GameApi.MapHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameApi.Map[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      GameApi.MapHelper.write (ostream, value[_i0]);
  }

}
