package GameApi;

/**
* GameApi/HashtableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Tuesday, June 23, 2020 8:11:46 AM IST
*/

public final class HashtableHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApi.Hashtable value = null;

  public HashtableHolder ()
  {
  }

  public HashtableHolder (GameApi.Hashtable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApi.HashtableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApi.HashtableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApi.HashtableHelper.type ();
  }

}
