package GameApi;


/**
* GameApi/Map.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Tuesday, June 23, 2020 8:11:46 AM IST
*/

public final class Map implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public int value = (int)0;

  public Map ()
  {
  } // ctor

  public Map (String _key, int _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class Map
