package GameApi;

/**
* GameApi/MapHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Tuesday, June 23, 2020 8:11:46 AM IST
*/

public final class MapHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApi.Map value = null;

  public MapHolder ()
  {
  }

  public MapHolder (GameApi.Map initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApi.MapHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApi.MapHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApi.MapHelper.type ();
  }

}
