package GameApi;

/**
* GameApi/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Tuesday, June 23, 2020 8:11:47 AM IST
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApi.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (GameApi.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApi.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApi.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApi.PlayerHelper.type ();
  }

}
