package GameApi;


/**
* GameApi/PlayerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Tuesday, June 23, 2020 8:11:47 AM IST
*/

public interface PlayerOperations 
{
  String createPlayerAccount (String username, String firstName, String lastName, int age, String password, String ip);
  boolean playerSignIn (String username, String password, String ip);
  String playerSignOut (String username, String ip);
  boolean transferAccount (String username, String password, String oldpassword, String newpassword);
} // interface PlayerOperations
